* Table of Contents                                            :TOC:noexport:
- [[#zig-tree-sitter-mode][Zig Tree Sitter Mode]]
- [[#installation][Installation]]
  - [[#use-package-emacs-30-or-later][use-package (Emacs 30 or later)]]
  - [[#elpaca][Elpaca]]
  - [[#straight][Straight]]
- [[#configuration][Configuration]]
  - [[#register-zig-ts-mode-with-eglot][Register zig-ts-mode with eglot]]
- [[#development][Development]]

* Zig Tree Sitter Mode

Official repository is at [[https://codeberg.org/meow_king/zig-ts-mode][CodeBerg]].

Target zig tree sitter grammar: [[https://github.com/tree-sitter-grammars/tree-sitter-zig][tree-sitter-zig]]. If the required
tree-sitter grammar is not installed, run ~M-x
zig-ts-install-grammars~ to install.

Requires Emacs 30.1 or later with tree-sitter support.  The navigation
settings use ~treesit-thing-settings~, introduced in Emacs 30.
The installed grammar must also match the ABI range supported by Emacs's
tree-sitter library; see ~treesit-library-abi-version~.  The current
upstream Zig grammar uses ABI 15.

-----

Currently I don't write Zig. If you'd like to help maintain or take
over this project, please contact me. Thank you!

* Installation

** use-package (Emacs 30 or later)

#+begin_src emacs-lisp
(use-package zig-ts-mode
  :vc ( :url "https://codeberg.org/meow_king/zig-ts-mode"
        :rev :newest))
#+end_src

** Elpaca

#+begin_src emacs-lisp
(use-package zig-ts-mode
  :ensure (:type git :host codeberg :repo "meow_king/zig-ts-mode"))
#+end_src

** Straight

#+begin_src emacs-lisp
(use-package zig-ts-mode
  :ensure '(:type git :host codeberg :repo "meow_king/zig-ts-mode"))
#+end_src

* Configuration

** Register zig-ts-mode with eglot

#+begin_src emacs-lisp
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(zig-ts-mode . ("zls"))))
#+end_src

* Development

Run ~just lint~ for byte-compilation checks and ~just test~ for ERT
regression tests.  Tests require the Zig grammar described above and
never install it automatically.  To use a grammar in a separate directory:

#+begin_src sh
ZIG_TS_GRAMMAR_DIR=/path/to/grammars just test
#+end_src

Set ~EMACS~ to select the Emacs executable.  ~just eval~ opens the Zig
examples for interactive inspection.
